version: "3.9"

networks:
  roboshop:
    driver: bridge

volumes:
  mysql:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ec2-user/mysql

  redis:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ec2-user/redis

  rabbitmq:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ec2-user/rabbitmq

  mongodb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ec2-user/mongodb

services:

  web:
    build: ./web
    image: web:v1
    container_name: web
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
      - cart
      - mysql
      - shipping
    networks:
      - roboshop

  mongodb:
    image: mongo:6
    container_name: mongodb
    volumes:
      - mongodb:/data/db
    networks:
      - roboshop

  catalogue:
    build: ./catalogue
    image: catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
    networks:
      - roboshop

  redis:
    image: redis
    container_name: redis
    volumes:
      - redis:/data
    networks:
      - roboshop

  user:
    build: ./user
    image: user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis
    networks:
      - roboshop

  cart:
    build: ./cart
    image: cart:v1
    container_name: cart
    depends_on:
      - redis
      - catalogue
    networks:
      - roboshop

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cities
      MYSQL_USER: roboshop
      MYSQL_PASSWORD: roboshop
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - roboshop

  shipping:
    build: ./shipping
    image: shipping:v1
    container_name: shipping
    depends_on:
      - mysql
    networks:
      - roboshop

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - roboshop

  payment:
    build: ./payment
    image: payment:v1
    container_name: payment
    depends_on:
      - rabbitmq
    networks:
      - roboshop

  ratings:
    build: ./ratings
    image: ratings:v1
    container_name: ratings
    depends_on:
      - mysql
    networks:
      - roboshop

